### ISSUE TITLE
Bump ubuntu base image in endpoint image

### ISSUE THREAD

**Issue by tatsuhiro-t** [quic-interop/quic-network-simulator#125]
simulator image got a upgrade to use ubuntu 22.04, but endpoint image is still 20.04.
Is there any chance to upgrade the base image of endpoint Dockerfile to 22.04 as well?

**Comment by marten-seemann** [comment]
I hope this would be fine, but I'm wondering if we'd be breaking people's builds.

**Comment by tatsuhiro-t** [comment]
I built ngtcp2 interop image with custom entrypoint image as ubuntu 22.04 base, and all interop tests succeeded except for A which has a known issue (see https://github.com/quic-interop/quic-interop-runner/pull/376).

>  but I'm wondering if we'd be breaking people's builds.

We can change the image name or tag, like:

- martenseemann/quic-network-simulator-endpoint:ubuntu-22.04
- martenseemann/quic-network-simulator-endpoint-v2:latest

etc

and tell people that old image will not get any update, and they should migrate their image to use new image.
What do you think about this?

**Comment by marten-seemann** [comment]
I think we should do it, and see if it actually breaks builds. If it does, we can just apply a Docker tag to the old image, to give people time to update their implemenations.
